[build]
publish = "dist"
command = "npm run build"

[[edge_functions]]
path = "/*"
function = "entry.netlify-edge"

[dev]
framework = "#static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200